### ISSUE TITLE
multiple errors... 

### ISSUE THREAD

**Issue by pocsag** [sh123/antenna_analyzer#2]
i downloaded all the libs.. i tried it on 2 different machines.. output stays like this
this is my output..
Arduino: 1.8.1 (Windows 7), Board:"Arduino Nano, ATmega328"

antenne_analyser2:31: error: no matching function for call to 'Rotary::Rotary(int, int, int)'

 Rotary g_rotary = Rotary(11, 12, 13);

                                    ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:31:36: note: candidates are:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:9:0:

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:27:5: note: Rotary::Rotary(char, char)

     Rotary(char, char);

     ^

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:27:5: note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:24:7: note: constexpr Rotary::Rotary(const Rotary&)

 class Rotary

       ^

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:24:7: note:   candidate expects 1 argument, 3 provided

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:24:7: note: constexpr Rotary::Rotary(Rotary&&)

C:\Users\joep\Documents\Arduino\libraries\Rotary/Rotary.h:24:7: note:   candidate expects 1 argument, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In function 'void setup()':

antenne_analyser2:83: error: no matching function for call to 'Si5351::init(int, int)'

   g_generator.init(SI5351_CRYSTAL_LOAD_6PF, 0);

                                              ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:83:46: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7: note: void Si5351::init(uint8_t, uint32_t, int32_t)

  void init(uint8_t, uint32_t, int32_t);

       ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7: note:   candidate expects 3 arguments, 2 provided

antenne_analyser2:85: error: no matching function for call to 'Si5351::set_freq(uint64_t&, long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0UL, SI5351_CLK2);

                                                            ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:85:60: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In function 'void swr_list_sweep_and_fill()':

antenne_analyser2:146: error: no matching function for call to 'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

       g_generator.set_freq(freq_hz, 0ULL, SI5351_CLK2);

                                                      ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:146:54: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note:   candidate expects 2 arguments, 3 provided

antenne_analyser2:166: error: no matching function for call to 'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:166:61: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In function 'void band_select_next()':

antenne_analyser2:217: error: no matching function for call to 'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:217:61: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In function 'void process_rotary()':

antenne_analyser2:270: error: no matching function for call to 'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

         g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                                   ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:270:67: note: candidate is:

In file included from C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10: note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In function 'void process_rotary_button()':

antenne_analyser2:294: error: 'class Rotary' has no member named 'process_button'

   unsigned char rotary_btn_state = g_rotary.process_button();

                                             ^

antenne_analyser2:298: error: 'BTN_NONE' was not declared in this scope

     case BTN_NONE:

          ^

antenne_analyser2:301: error: 'BTN_PRESSED' was not declared in this scope

     case BTN_PRESSED:

          ^

antenne_analyser2:305: error: 'BTN_RELEASED' was not declared in this scope

     case BTN_RELEASED:

          ^

antenne_analyser2:311: error: 'BTN_PRESSED_LONG' was not declared in this scope

     case BTN_PRESSED_LONG:

          ^

antenne_analyser2:317: error: 'BTN_RELEASED_LONG' was not declared in this scope

     case BTN_RELEASED_LONG:

          ^

exit status 1
no matching function for call to 'Rotary::Rotary(int, int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sh123** [comment]
Check README, requirements section, you need Rotary library from specific branch as default one does not support rotary encoder pushes.

**Comment by pocsag** [comment]
thanks for the reply!
i downloaded the lib from the link you've provided in the readme..
https://github.com/sh123/Rotary/tree/rotary_button

kind regards, joep

2017-09-07 16:44 GMT+02:00 sh123 <notifications@github.com>:

**Comment by pocsag** [comment]
there is another file now! this works!
but now for the next issue..
the si5351 lib seems not okay...

best wishes, joep
Arduino: 1.8.1 (Windows 7), Board:"Arduino Nano, ATmega328"

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void setup()':

antenne_analyser2:83: error: no matching function for call to
'Si5351::init(int, int)'

   g_generator.init(SI5351_CRYSTAL_LOAD_6PF, 0);

                                              ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:83:46:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7:
note: void Si5351::init(uint8_t, uint32_t, int32_t)

  void init(uint8_t, uint32_t, int32_t);

       ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7:
note:   candidate expects 3 arguments, 2 provided

antenne_analyser2:85: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0UL, SI5351_CLK2);

                                                            ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:85:60:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void swr_list_sweep_and_fill()':

antenne_analyser2:146: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

       g_generator.set_freq(freq_hz, 0ULL, SI5351_CLK2);

                                                      ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:146:54:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

antenne_analyser2:166: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:166:61:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void band_select_next()':

antenne_analyser2:217: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:217:61:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void process_rotary()':

antenne_analyser2:270: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

         g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                                   ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:270:67:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

exit status 1
no matching function for call to 'Si5351::init(int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


2017-09-07 16:55 GMT+02:00 Joep . <jindem@gmail.com>:

**Comment by sh123** [comment]
For synthesizer library.. need to check, but you can try to use older version, most likely they changed arguments, etc.

**Comment by pocsag** [comment]
okay,

which version should i use?

kind regards, joep pd1aef

2017-09-07 16:59 GMT+02:00 sh123 <notifications@github.com>:

**Comment by sh123** [comment]
It builds for me with anything below 2.0.0, e.g. 1.1.2

**Comment by pocsag** [comment]
hi,
i try to build it with 2.0.0
no good.. hope you have some advise.
this is the output;
Arduino: 1.8.1 (Windows 7), Board:"Arduino Nano, ATmega328"

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void setup()':

antenne_analyser2:83: error: no matching function for call to
'Si5351::init(int, int)'

   g_generator.init(SI5351_CRYSTAL_LOAD_6PF, 0);

                                              ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:83:46:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7:
note: void Si5351::init(uint8_t, uint32_t, int32_t)

  void init(uint8_t, uint32_t, int32_t);

       ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:283:7:
note:   candidate expects 3 arguments, 2 provided

antenne_analyser2:85: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0UL, SI5351_CLK2);

                                                            ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:85:60:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void swr_list_sweep_and_fill()':

antenne_analyser2:146: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

       g_generator.set_freq(freq_hz, 0ULL, SI5351_CLK2);

                                                      ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:146:54:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

antenne_analyser2:166: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:166:61:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void band_select_next()':

antenne_analyser2:217: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

   g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                             ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:217:61:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino: In
function 'void process_rotary()':

antenne_analyser2:270: error: no matching function for call to
'Si5351::set_freq(uint64_t&, long long unsigned int, si5351_clock)'

         g_generator.set_freq(g_active_band.freq, 0ULL, SI5351_CLK2);

                                                                   ^

C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:270:67:
note: candidate is:

In file included from
C:\Users\joep\Documents\Arduino\antenne_analyser2\antenne_analyser2.ino:8:0:

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note: uint8_t Si5351::set_freq(uint64_t, si5351_clock)

  uint8_t set_freq(uint64_t, enum si5351_clock);

          ^

C:\Users\joep\Documents\Arduino\libraries\Si5351Arduino\src/si5351.h:285:10:
note:   candidate expects 2 arguments, 3 provided

exit status 1
no matching function for call to 'Si5351::init(int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


2017-09-07 17:26 GMT+02:00 sh123 <notifications@github.com>:

**Comment by sh123** [comment]
Not less or equal 2.0.0, but less than 2.0.0, meaning anything starting with 1

**Comment by pocsag** [comment]
thanks! it worked this time!

thanks so much!

best wishes, joep

2017-09-07 18:25 GMT+02:00 sh123 <notifications@github.com>:

**Comment by sh123** [comment]
Good to know, thanks for helping with this project :)

**Comment by pocsag** [comment]
glad to be at help!

best wishes, joep, pd1aef

2017-09-07 19:33 GMT+02:00 sh123 <notifications@github.com>:
